### ISSUE TITLE
Unstable CI tests

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#249] opened 2021-06-07 07:18 UTC
**Describe the bug**
Tests running in CI sometime fail (without code change)

for example: 

> Task :backend:molgenis-emx2-webapi:compileTestJava

Note: /home/jenkins/agent/workspace/molgenis_molgenis-emx2_PR-233/backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/TestWebApi.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

> Task :backend:molgenis-emx2-sql:test FAILED

org.molgenis.emx2.sql.TestCompositeForeignKeys > testCompositeRefArray FAILED

    Add user failed: duplicate key value violates unique constraint "pg_authid_rolname_index".Key (rolname)=(MG_USER_admin) already exists.: SQL [CREATE ROLE "MG_USER_admin" WITH NOLOGIN]; ERROR: duplicate key value violates unique constraint "pg_authid_rolname_index"

      Detail: Key (rolname)=(MG_USER_admin) already exists.

        at org.molgenis.emx2.sql.SqlDatabaseExecutor.executeCreateUser(SqlDatabaseExecutor.java:34)

        at org.molgenis.emx2.sql.SqlDatabase.lambda$addUser$4(SqlDatabase.java:212)

        at org.molgenis.emx2.sql.SqlDatabase.lambda$tx$8(SqlDatabase.java:324)

        at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:615)

        at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:612)

        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:543)

        at org.jooq.impl.Tools$35$1.block(Tools.java:5242)

        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)

        at org.jooq.impl.Tools$35.get(Tools.java:5239)

        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:595)

        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:512)

        at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:612)

        at org.molgenis.emx2.sql.SqlDatabase.tx(SqlDatabase.java:316)

        at org.molgenis.emx2.sql.SqlDatabase.addUser(SqlDatabase.java:212)

        at org.molgenis.emx2.sql.SqlDatabase.init(SqlDatabase.java:112)

        at org.molgenis.emx2.sql.SqlDatabase.<init>(SqlDatabase.java:83)

        at org.molgenis.emx2.sql.TestDatabaseFactory.getTestDatabase(TestDatabaseFactory.java:30)

        at org.molgenis.emx2.sql.TestCompositeForeignKeys.setUp(TestCompositeForeignKeys.java:25)

        Caused by:

        org.jooq.exception.DataAccessException: SQL [CREATE ROLE "MG_USER_admin" WITH NOLOGIN]; ERROR: duplicate key value violates unique constraint "pg_authid_rolname_index"

**Comment by connoratrug** [comment] 2021-06-14 07:14
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce test parallelism for fixing flakey tests](https://trello.com/c/6vqiFjsm/113-reduce-test-parallelism-for-fixing-flakey-tests)

**Comment by mswertz** [comment] 2021-06-14 16:40
Lets see if the merge fixes this

**Comment by connoratrug** [comment] 2021-06-16 11:31
closing as new setup should fix it , if not can reopen

**Comment by connoratrug** [comment] 2021-06-23 12:43
https://jenkins.dev.molgenis.org/blue/organizations/jenkins/molgenis%2Fmolgenis-emx2/detail/PR-307/1/pipeline/

**Comment by mswertz** [comment] 2021-06-23 12:49
Interesting. This module -jobs afaik has no backend so must be related to another change (probably in deps from jackson or so). The error
`org.molgenis.emx2.tasks.TestTask > test1 FAILED

    internal error: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.molgenis.emx2.tasks.Step.getIndex()" is null (through reference chain: org.molgenis.emx2.tasks.DummyTask["steps"]->java.util.ArrayList[3]->org.molgenis.emx2.tasks.Task["description"])

        at org.molgenis.emx2.tasks.Step.toString(Step.java:134)

        at java.base/java.lang.String.valueOf(String.java:3365)

        at java.base/java.io.PrintStream.print(PrintStream.java:877)

        at org.gradle.internal.io.LinePerThreadBufferingOutputStream.println(LinePerThreadBufferingOutputStream.java:230)

        at org.molgenis.emx2.tasks.TestTask.test1(TestTask.java:21)



        Caused by:

        com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.molgenis.emx2.tasks.Step.getIndex()" is null (through reference chain: org.molgenis.emx2.tasks.DummyTask["steps"]->java.util.ArrayList[3]->org.molgenis.emx2.tasks.Task["description"])

            at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)

            at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)

            at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)

            at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:778)

            at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)

            at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)

            at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)

            at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)

            at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)

            at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)

            at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)

            at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)

            at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)

            at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)

            at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)

            at org.molgenis.emx2.tasks.Step.toString(Step.java:131)

            ... 4 more



            Caused by:

            java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.molgenis.emx2.tasks.Step.getIndex()" is null

                at org.molgenis.emx2.tasks.Step.getDescription(Step.java:57)

                at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:567)

                at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)

                at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)

                ... 16 more

`

**Comment by mswertz** [comment] 2021-06-23 12:50
Java version maybe?

**Comment by mswertz** [comment] 2021-07-21 19:59
should be closed in #302

**Closed by mswertz** 2021-07-21 19:59 UTC
Labels: bug
