### ISSUE TITLE
Diagnosis filter is broken

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3577] opened 2024-03-29 10:44 UTC
**What version of EMX2 are you using (see footer)**
v10.49.2

**Describe the bug**
When selecting a diagnosis, all biobank/collections are returned. For example for ICD-10 U07.1 I would expect 75 biobanks, 94 collections and 6 sub-collections (when using real BBMRI data). 

**To Reproduce**
1. Go to 'https://bbmri-emx2-test.molgeniscloud.org/ERIC/directory/#/catalogue'
2. Click on Diagnosis Filter
3. Scroll down to U07.1
4. See that the results are all biobanks (429).

**Expected behavior**
The diagnosis filter should result in the biobanks/collections that do have this diagnosis.

**Comment by chinook25** [comment] 2024-04-02 12:32
![searchresult](https://github.com/molgenis/molgenis-emx2/assets/5484559/3ea7617b-4f1f-44ec-ab16-7f97c4556a78)

Following your steps, the filter does seem to apply.

**Comment by chinook25** [comment] 2024-04-02 13:05
Hmm, did manage to recreate the bug, but not sure what I did different this time, will investigate more ;)

**Comment by chinook25** [comment] 2024-04-02 14:11
Might have to do with the race condition fixed in version v10.49.2, the server currently runs on v10.49.0. Can you upgrade the server and see if the issue is still present? @dtroelofsprins

**Comment by dtroelofsprins** [comment] 2024-04-03 07:00
That this is due to the race condition was indeed also my conclusion. The directory-emx2-acc.molgenis.net I explicitly didn't upgrade to 10.49.2 as external people are testing and don't want to introduce a new bug there.
I've just upgraded https://bbmri-emx2-test.molgeniscloud.org to 10.49.2, I've just selected U07.1 there and then I still get all biobanks, collections and sub-collections.

**Comment by dtroelofsprins** [comment] 2024-04-03 07:02
But as mentioned, with PR 3583, it seems to be fixed again?

**Closed** 2024-04-04 07:59 UTC
Labels: bug, priority, directory
