### ISSUE TITLE
Harmonisation matrix for repeated variable displayed incorrectly

### ISSUE THREAD

**Issue by hslh** [molgenis/molgenis-emx2#4286] opened 2024-09-30 13:39 UTC
**What version of EMX2 are you using (see footer)**
v11.15.3

**Describe the bug**
The harmonisation matrix is missing information, currently it's a series of rows with just the name of the cohort. It should be a matrix with the repeats of the variable in the rows and the resource name(s) as column(s), with cells containing mapping status. 

**To Reproduce**
1. Go to 'https://emx2.dev.molgenis.org/catalogue/ssr-catalogue/all/variables/'
2. Find the 'asthma_' variable and click on it. Click on 'asthma_'
3. Scroll down to 'Harmonisation status per data source'

**Expected behavior**
Show a matrix with the repeats of the variable in the rows and the resource name(s) as column(s), with cells containing mapping status. 

**Screenshots**
In dev:
![Screenshot 2024-09-30 at 15 48 59](https://github.com/user-attachments/assets/d76ef82a-da56-4bf2-ae45-36416e81d533)
In production (other data):
![Screenshot 2024-09-30 at 15 49 31](https://github.com/user-attachments/assets/dccdcaea-2119-456c-906f-319c847c7fbc)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 130.0.1

**Additional context:**
On the variable page for variable ‘asthma_’, there are no numberings anymore, which makes the harmonisation status unclear. It’s just a list of status indicators with the name of the cohort. See: $testCatalogue/ssr-catalogue/all/variables/asthma_-LifeCycle-outcome-LifeCycle?keys={"name":"asthma_","collection":{"id":"LifeCycle"},"dataset":{"name":"outcome","collection":{"id":"LifeCycle”}}}. (test 7 step 13)

**Comment by mswertz** [comment] 2024-10-11 13:16
cannot reproduce

**Comment by EleanorHyde-UMCG** [comment] 2024-10-22 14:34
This still a problem in acc: https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/variables/asthma_-LifeCycle-outcome-LifeCycle?keys={%22name%22:%22asthma_%22,%22resource%22:{%22id%22:%22LifeCycle%22},%22dataset%22:{%22name%22:%22outcome%22,%22resource%22:{%22id%22:%22LifeCycle%22}}}  I will try to recreate in dev.

**Comment by BrendaHijmans** [comment] 2024-10-23 10:34
This is only present in the test data, because the test data is a subset of the production data. The repeated variables that do not have a repeatMax filled out, get this representation in the UI. Can thus be fixed in the test data.

**Comment by BrendaHijmans** [comment] 2024-10-25 11:30
https://github.com/molgenis/molgenis-emx2/pull/4399

**Closed** 2024-10-30 14:01 UTC
Labels: priority, ssr-catalogue
